function [P,L,U] = LU_decomposition(A)
%Written by: Kapil Ahuja
%            (2014MT60663)
% The function is similar to the one in Gauss elimination. The matrix P is
% generated by performing same swap operations on Identity matrix, as done 
% in the pivoting step in each iteration and L matrix is generatd from
% ratios generated at each iteration.
%%
s = size(A);
n = s(1);
P = eye(n);
L = eye(n);
T = A;
for k = 1:n
    i_max = k;
    for i = k:n                                   %pivot
        if( abs(A(i,k)) > abs(A(i_max,k)) )
            i_max = i;
        end
    end
    if(A(i_max,k) == 0)                          % check for invertibility
        error('Matrix is non-invertible.');
    end
    A([k,i_max],:) = A([i_max,k],:);            % swap rows k and i_max of augmented matrix.
    P([k,i_max],:) = P([i_max,k],:);            % swap corresponding rows for the permutation matrix.
    for i = k+1:n
        ratio = A(i,k)/A(k,k);
        L(i,k) = ratio;
        for j = k+1:n
            A(i,j) = A(i,j) - ratio*A(k,j);
        end
        A(i,k)=0;
    end
end
U = A;
